# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catchCalculator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(523, 438)
        self.okButton = QtGui.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(420, 360, 81, 61))
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.dataFrame = QtGui.QFrame(Dialog)
        self.dataFrame.setGeometry(QtCore.QRect(20, 20, 211, 261))
        self.dataFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.dataFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.dataFrame.setObjectName(_fromUtf8("dataFrame"))
        self.levelLabel = QtGui.QLabel(self.dataFrame)
        self.levelLabel.setGeometry(QtCore.QRect(10, 60, 21, 20))
        self.levelLabel.setObjectName(_fromUtf8("levelLabel"))
        self.levelLine = QtGui.QLineEdit(self.dataFrame)
        self.levelLine.setGeometry(QtCore.QRect(80, 50, 113, 32))
        self.levelLine.setObjectName(_fromUtf8("levelLine"))
        self.pokemonLabel = QtGui.QLabel(self.dataFrame)
        self.pokemonLabel.setGeometry(QtCore.QRect(10, 20, 64, 20))
        self.pokemonLabel.setObjectName(_fromUtf8("pokemonLabel"))
        self.pokemonLine = QtGui.QLineEdit(self.dataFrame)
        self.pokemonLine.setGeometry(QtCore.QRect(80, 10, 113, 32))
        self.pokemonLine.setObjectName(_fromUtf8("pokemonLine"))
        self.hpLeftLine = QtGui.QLineEdit(self.dataFrame)
        self.hpLeftLine.setGeometry(QtCore.QRect(80, 90, 113, 32))
        self.hpLeftLine.setObjectName(_fromUtf8("hpLeftLine"))
        self.hpLeftLabel = QtGui.QLabel(self.dataFrame)
        self.hpLeftLabel.setGeometry(QtCore.QRect(10, 100, 71, 20))
        self.hpLeftLabel.setObjectName(_fromUtf8("hpLeftLabel"))
        self.caughtLine = QtGui.QLineEdit(self.dataFrame)
        self.caughtLine.setGeometry(QtCore.QRect(10, 190, 113, 32))
        self.caughtLine.setObjectName(_fromUtf8("caughtLine"))
        self.caughtLabel = QtGui.QLabel(self.dataFrame)
        self.caughtLabel.setGeometry(QtCore.QRect(10, 150, 191, 41))
        self.caughtLabel.setObjectName(_fromUtf8("caughtLabel"))
        self.levelLabel.raise_()
        self.levelLine.raise_()
        self.pokemonLabel.raise_()
        self.pokemonLine.raise_()
        self.hpLeftLine.raise_()
        self.hpLeftLabel.raise_()
        self.caughtLine.raise_()
        self.caughtLabel.raise_()
        self.boxesFrame = QtGui.QFrame(Dialog)
        self.boxesFrame.setGeometry(QtCore.QRect(240, 20, 261, 221))
        self.boxesFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.boxesFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.boxesFrame.setObjectName(_fromUtf8("boxesFrame"))
        self.ballBox = QtGui.QComboBox(self.boxesFrame)
        self.ballBox.setGeometry(QtCore.QRect(10, 40, 191, 31))
        self.ballBox.setObjectName(_fromUtf8("ballBox"))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballBox.addItem(_fromUtf8(""))
        self.ballLabel = QtGui.QLabel(self.boxesFrame)
        self.ballLabel.setGeometry(QtCore.QRect(10, 20, 64, 20))
        self.ballLabel.setObjectName(_fromUtf8("ballLabel"))
        self.oPowerLabel = QtGui.QLabel(self.boxesFrame)
        self.oPowerLabel.setGeometry(QtCore.QRect(10, 90, 121, 20))
        self.oPowerLabel.setObjectName(_fromUtf8("oPowerLabel"))
        self.opowerBox = QtGui.QComboBox(self.boxesFrame)
        self.opowerBox.setGeometry(QtCore.QRect(10, 110, 191, 31))
        self.opowerBox.setObjectName(_fromUtf8("opowerBox"))
        self.opowerBox.addItem(_fromUtf8(""))
        self.opowerBox.addItem(_fromUtf8(""))
        self.opowerBox.addItem(_fromUtf8(""))
        self.opowerBox.addItem(_fromUtf8(""))
        self.opowerBox.addItem(_fromUtf8(""))
        self.opowerBox.addItem(_fromUtf8(""))
        self.statusBox = QtGui.QComboBox(self.boxesFrame)
        self.statusBox.setGeometry(QtCore.QRect(10, 180, 191, 31))
        self.statusBox.setObjectName(_fromUtf8("statusBox"))
        self.statusBox.addItem(_fromUtf8(""))
        self.statusBox.addItem(_fromUtf8(""))
        self.statusBox.addItem(_fromUtf8(""))
        self.statusBox.addItem(_fromUtf8(""))
        self.statusBox.addItem(_fromUtf8(""))
        self.statusBox.addItem(_fromUtf8(""))
        self.statusLabel = QtGui.QLabel(self.boxesFrame)
        self.statusLabel.setGeometry(QtCore.QRect(10, 160, 121, 20))
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.resultTextBox = QtGui.QTextBrowser(Dialog)
        self.resultTextBox.setGeometry(QtCore.QRect(20, 290, 381, 131))
        self.resultTextBox.setObjectName(_fromUtf8("resultTextBox"))
        self.spriteLabel = QtGui.QLabel(Dialog)
        self.spriteLabel.setGeometry(QtCore.QRect(440, 300, 40, 32))
        self.spriteLabel.setText(_fromUtf8(""))
        self.spriteLabel.setObjectName(_fromUtf8("spriteLabel"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pokemonLine.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.okButton.setText(_translate("Dialog", "Calculate", None))
        self.levelLabel.setText(_translate("Dialog", "Lv.", None))
        self.pokemonLabel.setText(_translate("Dialog", "Pokemon", None))
        self.hpLeftLabel.setText(_translate("Dialog", "%HP Left.", None))
        self.caughtLabel.setText(_translate("Dialog", "\"Caught\" number in\n"
" National Pokédex", None))
        self.ballBox.setItemText(0, _translate("Dialog", "Poké Ball", None))
        self.ballBox.setItemText(1, _translate("Dialog", "Great Ball", None))
        self.ballBox.setItemText(2, _translate("Dialog", "Ultra Ball", None))
        self.ballBox.setItemText(3, _translate("Dialog", "Master Ball", None))
        self.ballBox.setItemText(4, _translate("Dialog", "Premier Ball", None))
        self.ballBox.setItemText(5, _translate("Dialog", "Net Ball", None))
        self.ballBox.setItemText(6, _translate("Dialog", "Nest Ball", None))
        self.ballBox.setItemText(7, _translate("Dialog", "Dive Ball", None))
        self.ballBox.setItemText(8, _translate("Dialog", "Repeat Ball", None))
        self.ballBox.setItemText(9, _translate("Dialog", "Timer Ball", None))
        self.ballBox.setItemText(10, _translate("Dialog", "Luxury Ball", None))
        self.ballBox.setItemText(11, _translate("Dialog", "Heal Ball", None))
        self.ballBox.setItemText(12, _translate("Dialog", "Quick Ball", None))
        self.ballBox.setItemText(13, _translate("Dialog", "Dusk Ball", None))
        self.ballLabel.setText(_translate("Dialog", "Ball", None))
        self.oPowerLabel.setText(_translate("Dialog", "Capture O-Power", None))
        self.opowerBox.setItemText(0, _translate("Dialog", "No power", None))
        self.opowerBox.setItemText(1, _translate("Dialog", "Capture Power Lv. 1", None))
        self.opowerBox.setItemText(2, _translate("Dialog", "Capture Power Lv. 2", None))
        self.opowerBox.setItemText(3, _translate("Dialog", "Capture Power Lv. 3", None))
        self.opowerBox.setItemText(4, _translate("Dialog", "Capture Power S", None))
        self.opowerBox.setItemText(5, _translate("Dialog", "Capture Power MAX", None))
        self.statusBox.setItemText(0, _translate("Dialog", "None", None))
        self.statusBox.setItemText(1, _translate("Dialog", "Paralyzed", None))
        self.statusBox.setItemText(2, _translate("Dialog", "Poisoned", None))
        self.statusBox.setItemText(3, _translate("Dialog", "Burned", None))
        self.statusBox.setItemText(4, _translate("Dialog", "Asleep", None))
        self.statusBox.setItemText(5, _translate("Dialog", "Frozen", None))
        self.statusLabel.setText(_translate("Dialog", "Status", None))

