# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(430, 486)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.formLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(230, 80, 181, 131))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.ball_box = QtGui.QComboBox(self.formLayoutWidget_2)
        self.ball_box.setObjectName(_fromUtf8("ball_box"))
        self.ball_box.addItem(_fromUtf8(""))
        self.ball_box.addItem(_fromUtf8(""))
        self.ball_box.addItem(_fromUtf8(""))
        self.ball_box.addItem(_fromUtf8(""))
        self.ball_box.addItem(_fromUtf8(""))
        self.ball_box.addItem(_fromUtf8(""))
        self.ball_box.addItem(_fromUtf8(""))
        self.ball_box.addItem(_fromUtf8(""))
        self.ball_box.addItem(_fromUtf8(""))
        self.ball_box.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.ball_box)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.status_box = QtGui.QComboBox(self.formLayoutWidget_2)
        self.status_box.setObjectName(_fromUtf8("status_box"))
        self.status_box.addItem(_fromUtf8(""))
        self.status_box.addItem(_fromUtf8(""))
        self.status_box.addItem(_fromUtf8(""))
        self.status_box.addItem(_fromUtf8(""))
        self.status_box.addItem(_fromUtf8(""))
        self.status_box.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.status_box)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtGui.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.captured_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.captured_edit.setObjectName(_fromUtf8("captured_edit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.captured_edit)
        self.label = QtGui.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label)
        self.formLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 80, 171, 131))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.pokemon_Name_box = QtGui.QComboBox(self.formLayoutWidget_3)
        self.pokemon_Name_box.setObjectName(_fromUtf8("pokemon_Name_box"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.pokemon_Name_box)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_3.setItem(1, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.level_edit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.level_edit.setObjectName(_fromUtf8("level_edit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.level_edit)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.hp_edit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.hp_edit.setObjectName(_fromUtf8("hp_edit"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.hp_edit)
        self.spriteLabel = QtGui.QLabel(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spriteLabel.sizePolicy().hasHeightForWidth())
        self.spriteLabel.setSizePolicy(sizePolicy)
        self.spriteLabel.setText(_fromUtf8(""))
        self.spriteLabel.setObjectName(_fromUtf8("spriteLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.spriteLabel)
        self.textBrowser = QtGui.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 260, 391, 192))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(335, 460, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.logolabel = QtGui.QLabel(Dialog)
        self.logolabel.setGeometry(QtCore.QRect(280, 20, 121, 51))
        self.logolabel.setText(_fromUtf8(""))
        self.logolabel.setObjectName(_fromUtf8("logolabel"))
        pixmap = QtGui.QPixmap("images/logo.png")
        self.logolabel.setPixmap(pixmap)
        self.logolabel.setMask(pixmap.mask())
        self.calculateButton = QtGui.QPushButton(Dialog)
        self.calculateButton.setGeometry(QtCore.QRect(340, 230, 72, 23))
        self.calculateButton.setObjectName(_fromUtf8("calculateButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Calculadora de captura", None))
        self.label_5.setText(_translate("Dialog", "Ball", None))
        self.ball_box.setItemText(0, _translate("Dialog", "Poké Ball", None))
        self.ball_box.setItemText(1, _translate("Dialog", "Super Ball", None))
        self.ball_box.setItemText(2, _translate("Dialog", "Ultra Ball", None))
        self.ball_box.setItemText(3, _translate("Dialog", "Master Ball", None))
        self.ball_box.setItemText(4, _translate("Dialog", "Honor Ball", None))
        self.ball_box.setItemText(5, _translate("Dialog", "Ocaso Ball", None))
        self.ball_box.setItemText(6, _translate("Dialog", "Sana Ball", None))
        self.ball_box.setItemText(7, _translate("Dialog", "Beast Ball", None))
        self.ball_box.setItemText(8, _translate("Dialog", "Gloria Ball", None))
        self.ball_box.setItemText(9, _translate("Dialog", "Nido Ball", None))
        self.label_6.setText(_translate("Dialog", "Status", None))
        self.status_box.setItemText(0, _translate("Dialog", "Ninguno", None))
        self.status_box.setItemText(1, _translate("Dialog", "Dormido", None))
        self.status_box.setItemText(2, _translate("Dialog", "Paralizado", None))
        self.status_box.setItemText(3, _translate("Dialog", "Congelado", None))
        self.status_box.setItemText(4, _translate("Dialog", "Quemado", None))
        self.status_box.setItemText(5, _translate("Dialog", "Envenenado", None))
        self.captured_edit.setText(_translate("Dialog", "0", None))
        self.label.setText(_translate("Dialog", "Nº pkmn capt.", None))
        self.label_8.setText(_translate("Dialog", "Pokemon", None))
        self.label_9.setText(_translate("Dialog", "Nivel", None))
        self.level_edit.setText(_translate("Dialog", "10", None))
        self.label_10.setText(_translate("Dialog", "%HP restante", None))
        self.hp_edit.setText(_translate("Dialog", "100", None))
        self.label_3.setText(_translate("Dialog", "by Carchenilla", None))
        self.label_4.setText(_translate("Dialog", "La calculadora molona del Carche 2.0", None))
        self.calculateButton.setText(_translate("Dialog", "Calculate", None))

